### PR TITLE
DTSPO-13832 - Add depends_on for app insights

### PR DESCRIPTION
**Pull request by endakelly**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/DTSPO-13832

### Change description ###
Fixing error related to app insights being in region disallowed by policy

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by timja — CHANGES_REQUESTED** [review]
update line 4 instead to use an output from the resource

explicit dependencies should only be used in very limited situations
https://developer.hashicorp.com/terraform/tutorials/configuration-language/dependencies#manage-explicit-dependencies

**Comment by endakelly** [comment]
> update line 4 instead to use an output from the resource
> 
> explicit dependencies should only be used in very limited situations [developer.hashicorp.com/terraform/tutorials/configuration-language/dependencies#manage-explicit-dependencies](https://developer.hashicorp.com/terraform/tutorials/configuration-language/dependencies#manage-explicit-dependencies)

That was my initial thought as well but the resource doesn't export a name atrtibute https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights#attributes-reference

The app insights instance isn't showing up as to be created nor is it in the state which is odd. Do you think this lifecycle block could be the cause and is it still needed? https://github.com/hmcts/draft-store/blob/121251a870c6f79453d456e930ecbb7f5e14f579/infrastructure/main.tf#L184-L189

Could also just not create any app insights related resources in sbox.

**Comment by endakelly** [comment]
Ignore my last, actually just noticed there is an error about being denied by policy due to the location being West Europe. Seems like it was set to that a few years ago, maybe when UK South wasn't live. Would it be best to add an exemption to allow app insights to exist in West Europe or move the existing ones to UK South? I'd imagine that would delete the existing insights data and I don't see a move option in the portal.

**Comment by timja** [comment]
> Ignore my last, actually just noticed there is an error about being denied by policy due to the location being West Europe. Seems like it was set to that a few years ago, maybe when UK South wasn't live. Would it be best to add an exemption to allow app insights to exist in West Europe or move the existing ones to UK South? I'd imagine that would delete the existing insights data and I don't see a move option in the portal.

just re-create in uk south i think

**Review by timja — APPROVED** [review]

**Pull request merged**
