### PR TITLE
Add Postgres11 Database and required secrets

### PR DESCRIPTION
**Pull request by gbstan92**
Adding a new postgres 11 database in preparation for the migration.

**Does this PR introduce a breaking change?** (check one with "x")

```
[] Yes
[x] No
```

### CODE REVIEW

**Comment by timja** [comment]
something very wrong in this branch git history

**Comment by gbstan92** [comment]
> something very wrong in this branch git history

Should I delete and re-create this from master?

**Comment by timja** [comment]
yes please

**Comment by gbstan92** [comment]
Recreate demo branch is required first

**Pull request closed without merging**
